# Generated by Django 5.1.1 on 2024-11-09 21:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_product_recipe'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Recipe',
        ),
    ]
